# Generated by Django 3.0.7 on 2020-06-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('Product', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Indian', models.CharField(max_length=50)),
                ('Foriegns', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=50)),
                ('Indian', models.CharField(max_length=50)),
                ('Foriegns', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
