# Generated by Django 3.0.7 on 2020-06-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorytree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categories', models.CharField(max_length=50)),
                ('Subcat', models.CharField(max_length=50, null=True)),
                ('Product', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
