# Generated by Django 3.0.7 on 2020-06-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0002_categorytree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytree',
            name='Categories',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
