# Generated by Django 3.0.7 on 2020-06-28 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0003_auto_20200629_0448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='app',
        ),
    ]
