# Generated by Django 3.0.7 on 2020-06-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0004_delete_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categories', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
