# Generated by Django 3.0.7 on 2020-06-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categorytree',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AlterField(
            model_name='category',
            name='Categories',
            field=models.CharField(max_length=50),
        ),
    ]
