# Generated by Django 3.0.7 on 2020-06-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0007_productslevelone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productslevelone',
            old_name='Category',
            new_name='Categories',
        ),
    ]
