# Generated by Django 3.0.7 on 2020-06-30 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0010_auto_20200701_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(max_length=50)),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extomodapp.category', verbose_name='Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Productslevelone',
        ),
    ]
