# Generated by Django 3.0.7 on 2020-06-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0012_auto_20200701_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='Categories',
            new_name='category_id',
        ),
    ]
