# Generated by Django 3.0.7 on 2020-06-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0013_auto_20200701_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategoryname',
            new_name='subcategory_name',
        ),
    ]
