# Generated by Django 3.0.7 on 2020-07-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0015_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='subcategory_id',
            new_name='subcategory_name',
        ),
    ]
