# Generated by Django 3.0.7 on 2020-07-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0018_auto_20200702_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_choices',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product_choices',
            name='subcategory_id',
        ),
    ]
