# Generated by Django 3.0.7 on 2020-07-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0019_auto_20200703_0012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_choices',
        ),
    ]
