# Generated by Django 3.0.7 on 2020-07-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0022_auto_20200703_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_product',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
