# Generated by Django 3.0.7 on 2020-07-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0023_auto_20200703_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='main_product',
            name='subcategory_id',
        ),
    ]
