# Generated by Django 3.0.5 on 2020-07-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extomodapp', '0026_auto_20200706_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='main_product',
        ),
    ]
